### ISSUE TITLE
PRACT.7. ENTREVISTA

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipomana#1]
[PRACTICA7_EQUIPO.MANA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-practica-de-entrevista-cuestionarios-etc-equipomana/files/13197154/PRACTICA7_EQUIPO.MANA.pdf)

**Comment by saul19bautista** [comment]
portada = 25%
Procedimiento = 25%
Figuras, ilustraciones y fotografías = 25%
Resultados y conclusiones =25% 
total 100 /100
calificación 20
El trabajo está bien desarrollado

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
